
server:
  port: 8095
  session-timeout: 30
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver


  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  servlet:
    multipart:
      max-file-size: 100000000
      max-request-size: 100000000

#mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ex.project.model

save:
  path: E:/Ahtah/CompanySvn/bishe/bisheUI/static/img/goodsImg/